"""
G-code generator module for WoodWOP Post Processor.
Handles generation of standard G-code from FreeCAD Path objects.
"""

from . import config
from . import utils

# Try to import parallel G-code post processor
try:
    import woodwop_gcode_post
    HAS_GCODE_POST = True
except ImportError:
    HAS_GCODE_POST = False


def generate_gcode(objectslist):
    """
    Generate standard G-code from FreeCAD Path objects using parallel post processor.
    
    NOTE: This function does NOT apply coordinate system offsets (G54, G55, etc.).
    G-code coordinates remain unchanged regardless of COORDINATE_SYSTEM setting.
    Only MPR format applies coordinate offsets.
    
    Args:
        objectslist: List of FreeCAD Path objects
        
    Returns:
        str: G-code content
    """
    try:
        if HAS_GCODE_POST:
            # Generate G-code using the dedicated post processor
            gcode_content = woodwop_gcode_post.export(objectslist, "-", "--no-show-editor --no-header")
            # Ensure we return a string, not bool or None
            if isinstance(gcode_content, bool):
                print(f"[WoodWOP WARNING] G-code post processor returned bool: {gcode_content}, using fallback")
                raise ValueError("G-code post processor returned bool instead of string")
            if not gcode_content or not isinstance(gcode_content, str):
                print(f"[WoodWOP WARNING] G-code post processor returned invalid type: {type(gcode_content)}, using fallback")
                raise ValueError(f"G-code post processor returned invalid type: {type(gcode_content)}")
            return gcode_content
    except Exception as e:
        print(f"[WoodWOP WARNING] Failed to use parallel G-code post processor: {e}")
        print(f"[WoodWOP WARNING] Falling back to simple G-code generation")
    
    # Fallback: simple G-code generation
    gcode_lines = []
    
    # Header
    gcode_lines.append("(Generated by FreeCAD WoodWOP Post Processor)")
    gcode_lines.append(f"(Date: {config.now.strftime('%Y-%m-%d %H:%M:%S')})")
    gcode_lines.append("")
    gcode_lines.append(config.UNITS)  # G21 for metric
    gcode_lines.append("G90")  # Absolute coordinates
    gcode_lines.append("G40")  # Cancel cutter compensation
    gcode_lines.append("")
    
    # Process all path objects
    for obj in objectslist:
        if not hasattr(obj, "Path"):
            continue
        
        # Add operation comment
        if config.OUTPUT_COMMENTS:
            gcode_lines.append(f"(Operation: {obj.Label if hasattr(obj, 'Label') else 'Unknown'})")
        
        # Process path commands
        path_commands = obj.Path.Commands if hasattr(obj.Path, 'Commands') else []
        for cmd in path_commands:
            line = cmd.Name
            
            # Special handling for cutter compensation commands (G41/G42)
            if cmd.Name in ['G41', 'G41.1', 'G42', 'G42.1']:
                # G41 - Left cutter radius compensation
                # G41.1 - Dynamic left cutter radius compensation
                # G42 - Right cutter radius compensation
                # G42.1 - Dynamic right cutter radius compensation
                
                # Add D parameter (cutter compensation number)
                if 'D' in cmd.Parameters:
                    # Use D parameter from command
                    line += f" D{int(cmd.Parameters['D'])}"
                else:
                    # Use tool number as default D value
                    # Import here to avoid circular dependency
                    from . import job_processor
                    tool_number = job_processor.get_tool_number(obj)
                    if tool_number:
                        line += f" D{tool_number}"
                
                # Add other parameters (X, Y, Z, I, J, etc.)
                for param, value in sorted(cmd.Parameters.items()):
                    if param != 'D':  # D already added above
                        line += f" {param}{utils.fmt(value)}"
            else:
                # Regular command - add all parameters
                for param, value in sorted(cmd.Parameters.items()):
                    line += f" {param}{utils.fmt(value)}"
            
            gcode_lines.append(line)
        
        if config.OUTPUT_COMMENTS:
            gcode_lines.append("(End operation)")
            gcode_lines.append("")
    
    # Footer
    gcode_lines.append("M2")  # Program end
    gcode_lines.append("")
    
    return "\n".join(gcode_lines)

