# WoodWOP G-code Post Processor for FreeCAD
# Parallel G-code output for WoodWOP post processor
# Generates standard G-code alongside MPR format

import FreeCAD
import Path
import Path.Post.Utils as PostUtils
import PathScripts.PathUtils as PathUtils
import datetime
import argparse
import shlex
from builtins import open as pyopen

TOOLTIP = """
Generate standard G-code from a Path that is compatible with most CNC controllers.
This post processor generates G-code in parallel with WoodWOP MPR format.
import woodwop_gcode_post
woodwop_gcode_post.export(object, "/path/to/file.nc")
"""

now = datetime.datetime.now()

parser = argparse.ArgumentParser(prog="woodwop_gcode", add_help=False)
parser.add_argument("--no-header", action="store_true", help="suppress header output")
parser.add_argument("--no-comments", action="store_true", help="suppress comment output")
parser.add_argument("--line-numbers", action="store_true", help="prefix with line numbers")
parser.add_argument(
    "--no-show-editor",
    action="store_true",
    help="don't pop up editor before writing output",
)
parser.add_argument("--precision", default="3", help="number of digits of precision, default=3")
parser.add_argument(
    "--preamble",
    help='set commands to be issued before the first command, default="G17\nG90\nG21"',
)
parser.add_argument(
    "--postamble",
    help='set commands to be issued after the last command, default="M5\nG17 G90\nM2"',
)
parser.add_argument(
    "--inches", action="store_true", help="Convert output for US imperial mode (G20)"
)

TOOLTIP_ARGS = parser.format_help()

# Globals set customization preferences
OUTPUT_COMMENTS = True
OUTPUT_HEADER = True
OUTPUT_LINE_NUMBERS = False
SHOW_EDITOR = False  # Don't show editor for parallel output
MODAL = False  # if true commands are suppressed if the same as previous line.
OUTPUT_DOUBLES = True  # if false duplicate axis values are suppressed
COMMAND_SPACE = " "
LINENR = 100  # line number starting value
LINEINCR = 10  # line number increment

# Machine configuration
UNITS = "G21"  # G21 for metric, G20 for us standard
UNIT_SPEED_FORMAT = "mm/min"
UNIT_FORMAT = "mm"

MACHINE_NAME = "Generic CNC"
CORNER_MIN = {"x": 0, "y": 0, "z": 0}
CORNER_MAX = {"x": 500, "y": 300, "z": 300}

# Preamble text will appear at the beginning of the gCode output file.
PREAMBLE = """G17 G90 G21
"""

# Postamble text will appear following the last operation.
POSTAMBLE = """M5
G17 G90
M2
"""


def fmt(value, units=None):
    """Format a value with the specified precision."""
    if units is None:
        units = UNIT_FORMAT
    if isinstance(value, (int, float)):
        precision = int(PRECISION)
        if precision < 0:
            precision = 0
        return f"{value:.{precision}f}"
    return str(value)


def linenumber():
    """Return a line number if enabled."""
    global LINENR
    if OUTPUT_LINE_NUMBERS:
        LINENR += LINEINCR
        return f"N{LINENR} "
    return ""


def export(objectslist, filename, argstring):
    """Main export function called by FreeCAD."""
    global OUTPUT_COMMENTS, OUTPUT_HEADER, OUTPUT_LINE_NUMBERS, SHOW_EDITOR, PRECISION
    global PREAMBLE, POSTAMBLE, UNITS

    # Parse arguments
    args = parser.parse_args(shlex.split(argstring))
    
    OUTPUT_COMMENTS = not args.no_comments
    OUTPUT_HEADER = not args.no_header
    OUTPUT_LINE_NUMBERS = args.line_numbers
    SHOW_EDITOR = not args.no_show_editor
    
    if args.precision:
        PRECISION = int(args.precision)
    
    if args.preamble:
        PREAMBLE = args.preamble
    
    if args.postamble:
        POSTAMBLE = args.postamble
    
    if args.inches:
        UNITS = "G20"
    else:
        UNITS = "G21"

    # Initialize output
    gcode = []
    
    # Write header
    if OUTPUT_HEADER:
        gcode.append(linenumber() + "(Generated by FreeCAD)")
        gcode.append(linenumber() + f"(Post Processor: {__name__})")
        gcode.append(linenumber() + f"(Output Time: {now.strftime('%Y-%m-%d %H:%M:%S')})")
        gcode.append("")

    # Write preamble
    for line in PREAMBLE.splitlines(False):
        if line.strip():
            gcode.append(linenumber() + line)
    gcode.append(linenumber() + UNITS)
    gcode.append("")

    # Process all path objects
    for obj in objectslist:
        if not hasattr(obj, "Path"):
            continue

        # Add operation comment
        if OUTPUT_COMMENTS:
            gcode.append(linenumber() + f"(Begin operation: {obj.Label if hasattr(obj, 'Label') else 'Unknown'})")

        # Process path commands
        lastcommand = None
        lastparams = {}
        for cmd in PathUtils.getPathWithPlacement(obj).Commands:
            outstring = ""
            command = cmd.Name
            
            # Skip modal commands if MODAL is enabled
            if MODAL and command == lastcommand:
                outstring = ""
            else:
                outstring += linenumber()
                outstring += command
                lastcommand = command

            # Add parameters
            for param, value in sorted(cmd.Parameters.items()):
                if param in ["X", "Y", "Z", "A", "B", "C", "I", "J", "K", "F", "S", "T", "Q", "R", "L", "P"]:
                    if OUTPUT_DOUBLES or param not in lastparams or lastparams[param] != value:
                        outstring += f"{COMMAND_SPACE}{param}{fmt(value)}"
                        lastparams[param] = value
                else:
                    outstring += f"{COMMAND_SPACE}{param}{fmt(value)}"

            if outstring:
                gcode.append(outstring)

        if OUTPUT_COMMENTS:
            gcode.append(linenumber() + f"(End operation: {obj.Label if hasattr(obj, 'Label') else 'Unknown'})")
            gcode.append("")

    # Write postamble
    if OUTPUT_COMMENTS:
        gcode.append(linenumber() + "(Begin postamble)")
    for line in POSTAMBLE.splitlines(False):
        if line.strip():
            gcode.append(linenumber() + line)

    # Join all lines
    final = "\n".join(gcode)

    # Show editor if requested
    if FreeCAD.GuiUp and SHOW_EDITOR:
        dia = PostUtils.GCodeEditorDialog()
        dia.editor.setText(final)
        result = dia.exec_()
        if result:
            final = dia.editor.toPlainText()

    # Write to file
    if filename != "-":
        gfile = pyopen(filename, "wb")
        gfile.write(final.encode("utf-8"))
        gfile.close()
        print(f"✓ G-code file written: {filename}")

    return final


def parse(argstring):
    """Parse arguments and return namespace."""
    return parser.parse_args(shlex.split(argstring))

